[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "pip"]

[phases.install]
cmds = [
  "cd backend && npm ci --only=production",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && node server.js"
