[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "pip"]

[phases.install]
cmds = [
  "cd backend && npm install --production",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && node server.js"
