[phases.setup]
nixPkgs = ["nodejs", "npm", "python3", "pip"]

[phases.install]
cmds = [
  "cd backend && npm ci --only=production",
  "cd frontend && npm ci --only=production",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"
